language: objective-c
before_script:
    - export LANG=en_US.UTF-8

before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - pod install
script:xcodebuild -workspace PGdev.xcworkspace -scheme PGdev -sdk iphonesimulator -configuration Release clean test 


